// One bespoke illustration per story, keyed by story id.
// Generated by tools/build_story_art.py — do not hand-edit.
// Each value is a complete 320x180 SVG showing what that story actually says.
const STORY_ART = {};
const QUEST = null;
