#!/usr/bin/env python3
"""Turn the character-art workflow output into js/characters.js.

Every SVG is sanitised before it is written, because art authored by a model can
carry things that quietly break a page: markdown fences, an XML declaration,
width/height that fights the CSS, <script>, or duplicate gradient ids that make
one character steal another's colours.

  python3 tools/build_characters.py <journal.jsonl>
"""
import json
import os
import re
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Keep ALL scratch files inside the project — never the system temp dir.
_WORK = os.path.join(ROOT, '.work', 'tmp')
os.makedirs(_WORK, exist_ok=True)
tempfile.tempdir = _WORK

OUT = os.path.join(ROOT, 'js', 'characters.js')

BANNED = re.compile(r'<(script|style|text|image|foreignObject|use)\b', re.I)


def load(journal):
    art = {}
    with open(journal, encoding='utf-8') as f:
        for line in f:
            try:
                e = json.loads(line)
            except json.JSONDecodeError:
                continue
            if e.get('type') != 'result':
                continue
            r = e.get('result') or e.get('value')
            if isinstance(r, str):
                try:
                    r = json.loads(r)
                except json.JSONDecodeError:
                    continue
            if isinstance(r, dict) and r.get('key') and r.get('svg'):
                # later entries are the reviewed/repaired versions
                art[r['key']] = r
    return art


def clean(key, svg):
    s = svg.strip()
    s = re.sub(r'^```[a-z]*\s*', '', s)
    s = re.sub(r'\s*```$', '', s)
    s = re.sub(r'<\?xml.*?\?>', '', s, flags=re.S)
    s = re.sub(r'<!DOCTYPE.*?>', '', s, flags=re.S | re.I)
    s = re.sub(r'<!--.*?-->', '', s, flags=re.S)
    i = s.find('<svg')
    if i < 0:
        return None, 'no <svg> element'
    j = s.rfind('</svg>')
    if j < 0:
        return None, 'unclosed <svg>'
    s = s[i:j + 6]

    if BANNED.search(s):
        return None, 'contains a banned element'
    if 'viewBox' not in s:
        return None, 'no viewBox'

    # let CSS own the size
    s = re.sub(r'\s(width|height)="[^"]*"', '', s, count=2)
    # namespace every id so two characters on one page cannot collide
    ids = set(re.findall(r'id="([^"]+)"', s))
    for old in ids:
        new = f'{key}-{old}' if not old.startswith(key + '-') else old
        s = s.replace(f'id="{old}"', f'id="{new}"')
        s = s.replace(f'url(#{old})', f'url(#{new})')
        s = s.replace(f'"#{old}"', f'"#{new}"')
    s = re.sub(r'\s+', ' ', s).strip()
    return s, None


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    art = load(sys.argv[1])
    good, bad = {}, []
    for key, rec in sorted(art.items()):
        svg, err = clean(key, rec['svg'])
        if err:
            bad.append((key, err))
        else:
            good[key] = {'name': rec.get('name', key), 'svg': svg}

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('// Hand-drawn characters, inlined as SVG.\n')
        f.write('// Generated by tools/build_characters.py — do not hand-edit.\n')
        f.write('// Ids are namespaced per character so gradients cannot collide.\n')
        f.write('const CHARACTERS = {\n')
        for key, v in good.items():
            f.write(f"  {key}: {json.dumps(v['svg'])},\n")
        f.write('};\n')
        f.write('const CHARACTER_NAMES = ')
        f.write(json.dumps({k: v['name'] for k, v in good.items()}, indent=1))
        f.write(';\n')

    print(f'wrote {len(good)} characters to {OUT}')
    total = sum(len(v['svg']) for v in good.values())
    print(f'total inline size: {total/1024:.1f} KB')
    for key, err in bad:
        print(f'  REJECTED {key}: {err}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
