#!/usr/bin/env python3
"""Turn the story-art workflow output into js/story-art.js.

Every SVG is sanitised before shipping: model-authored art can carry markdown
fences, an XML declaration, width/height that fights the layout, banned
elements, or duplicate gradient ids that make one picture steal another's
colours.

  python3 tools/build_story_art.py <result.json>
"""
import json
import os
import re
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Keep ALL scratch files inside the project — never the system temp dir.
_WORK = os.path.join(ROOT, '.work', 'tmp')
os.makedirs(_WORK, exist_ok=True)
tempfile.tempdir = _WORK

OUT = os.path.join(ROOT, 'js', 'story-art.js')
BANNED = re.compile(r'<(script|style|text|image|foreignObject|use)\b', re.I)


def clean(key, svg):
    s = svg.strip()
    s = re.sub(r'^```[a-z]*\s*', '', s)
    s = re.sub(r'\s*```$', '', s)
    s = re.sub(r'<\?xml.*?\?>', '', s, flags=re.S)
    s = re.sub(r'<!--.*?-->', '', s, flags=re.S)
    i, j = s.find('<svg'), s.rfind('</svg>')
    if i < 0 or j < 0:
        return None, 'no <svg>'
    s = s[i:j + 6]
    if BANNED.search(s):
        return None, 'banned element'
    if 'viewBox' not in s:
        return None, 'no viewBox'
    s = re.sub(r'\s(width|height)="[^"]*"', '', s, count=2)
    for old in set(re.findall(r'id="([^"]+)"', s)):
        new = old if old.startswith(key + '-') else f'{key}-{old}'
        s = s.replace(f'id="{old}"', f'id="{new}"').replace(f'url(#{old})', f'url(#{new})')
    return re.sub(r'\s+', ' ', s).strip(), None


def main():
    raw = open(sys.argv[1], encoding='utf-8').read()
    i = raw.find('"result"')
    j = raw.find('{', i)
    depth, data = 0, None
    for k, ch in enumerate(raw[j:], j):
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                data = json.loads(raw[j:k + 1])
                break
    if not data:
        print('could not parse workflow result')
        return 1

    good, bad = {}, []
    for rec in data.get('scenes', []):
        if not rec or not rec.get('id') or not rec.get('svg'):
            continue
        svg, err = clean(rec['id'], rec['svg'])
        if err:
            bad.append((rec['id'], err))
        else:
            good[rec['id']] = svg

    quest = data.get('quest')
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('// One bespoke illustration per story, keyed by story id.\n')
        f.write('// Generated by tools/build_story_art.py — do not hand-edit.\n')
        f.write('const STORY_ART = {\n')
        for k, v in sorted(good.items()):
            f.write(f'  {json.dumps(k)}: {json.dumps(v)},\n')
        f.write('};\n')
        f.write('const QUEST = ' + json.dumps(quest, indent=1) + ';\n')

    total = sum(len(v) for v in good.values())
    print(f'wrote {len(good)} story illustrations ({total/1024:.1f} KB)')
    if quest:
        print(f'quest: {len(quest.get("beats", []))} island beats, '
              f'{len(quest.get("lands", []))} lands')
        print('premise:', (quest.get('premise') or '')[:150])
    for k, e in bad:
        print('  REJECTED', k, e)
    return 0


if __name__ == '__main__':
    sys.exit(main())
