#!/usr/bin/env python3
"""Extract the hand-drawn creature art from the classic app into creatures.js.

These 28 SVGs already exist and are genuinely charming — far better than emoji
— so the reward system uses them rather than inventing new art.

Each creature also gets a one-line cheer, said in the unlock moment. They are
written to sound like a friend arriving, not a trophy being issued.

  python3 dev/build_creatures.py
"""
import json
import os
import re
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_WORK = os.path.join(ROOT, '.work', 'tmp')
os.makedirs(_WORK, exist_ok=True)
tempfile.tempdir = _WORK

# Unlock order. Deliberately varied so two similar animals never arrive back to
# back, and the first few are the most immediately lovable.
ORDER = [
    'pip',       # free starter — the app's own unicorn
    'mimi', 'biscuit', 'bun', 'peep', 'nova', 'flutter', 'ember', 'dot',
    'pinky', 'sage', 'marina', 'rexy', 'bamboo', 'sheldon', 'dottie',
    'clover', 'inky', 'nutmeg', 'grace', 'waddle', 'blaze', 'stretch',
    'twinkle', 'sparkle', 'splash', 'snuggles', 'whiskers',
]

CHEER = {
    'pip': 'Let\'s read together!',
    'mimi': 'I purr when you read!',
    'biscuit': 'You read that so well!',
    'bun': 'I hopped over to hear you!',
    'peep': 'I just hatched to listen!',
    'nova': 'You are a real star!',
    'flutter': 'I fluttered here for you!',
    'ember': 'I heard you all the way here!',
    'dot': 'Reading makes me sparkle!',
    'pinky': 'I stood on one leg to listen!',
    'sage': 'Whooo is a good reader? You!',
    'marina': 'I swam up to hear that!',
    'rexy': 'That was a mighty good read!',
    'bamboo': 'You read better than I chew!',
    'sheldon': 'Slow and steady, just like reading!',
    'dottie': 'Spot on reading!',
    'clover': 'You are my lucky friend!',
    'inky': 'Eight arms, all clapping!',
    'nutmeg': 'I stored up all your words!',
    'grace': 'That was beautiful reading!',
    'waddle': 'I waddled a long way to hear you!',
    'blaze': 'Your reading is on fire!',
    'stretch': 'I can see how far you have come!',
    'twinkle': 'You make the whole sky twinkle!',
    'sparkle': 'Sparkles for every word!',
    'splash': 'You made a big splash!',
    'snuggles': 'Come read to me any time!',
    'whiskers': 'My whiskers wiggle when you read!',
}


def main():
    src = open(os.path.join(ROOT, 'classic/js/characters.js'), encoding='utf-8').read()
    chars = {}
    for m in re.finditer(r'^  ([a-z]+): ("(?:[^"\\]|\\.)*"),$', src, re.M):
        chars[m.group(1)] = json.loads(m.group(2))
    names = json.loads(re.search(r'const CHARACTER_NAMES = (\{[\s\S]*?\});', src).group(1))

    missing = [k for k in ORDER if k not in chars]
    if missing:
        raise SystemExit(f'missing art for: {missing}')
    extra = [k for k in chars if k not in ORDER]
    if extra:
        print(f'note: {len(extra)} creatures not in the unlock order: {extra}')

    # An SVG <rect> with no width/height paints NOTHING. Sparkle shipped with
    # a missing leg this way, invisible until someone looked closely. Never
    # let that through silently again.
    broken = []
    for key in ORDER:
        for tag in re.findall(r'<rect[^>]*>', chars[key]):
            if 'width=' not in tag or 'height=' not in tag:
                broken.append(f'{key}: {tag}')
    if broken:
        raise SystemExit('unsized <rect> paints nothing:\n  ' + '\n  '.join(broken))

    out = []
    for key in ORDER:
        svg = chars[key]
        # Ids are already namespaced per character in the source; keep as-is.
        out.append({
            'k': key,
            'n': names.get(key, key.title()),
            'c': CHEER.get(key, 'You read that so well!'),
            'svg': svg,
        })

    path = os.path.join(ROOT, 'creatures.js')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('// Creature friends, earned by reading. Art lifted from the classic app.\n')
        f.write('// Generated by dev/build_creatures.py — do not hand-edit.\n')
        f.write('const CREATURES = ' + json.dumps(out, separators=(',', ':')) + ';\n')
    print(f'wrote {len(out)} creatures to {path} ({os.path.getsize(path)/1024:.0f} KB)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
