#!/usr/bin/env python3
"""Rebuild content.js for Reading Star from the classic app's curriculum.

The classic app under classic/ already holds graded, decodable words (its
word banks and activities) and real story sentences — and every word clip in
its audio manifest was transcription-verified. This pulls them out into the
flat lists the simple app reads.

  python3 dev/build_content.py
"""
import json
import os
import re
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Keep ALL scratch files inside the project — never the system temp dir.
_WORK = os.path.join(ROOT, '.work', 'tmp')
os.makedirs(_WORK, exist_ok=True)
tempfile.tempdir = _WORK


def split_sentences(page):
    """Split a story page into sentences a child can read off a card.

    Splitting on sentence-enders alone tears quoted dialogue apart, leaving
    fragments with a dangling quote mark — `"Help!` or `I can not stop!"` —
    which look like a mistake on a big display card. So: keep a quoted span
    whole, and if a fragment still ends up with unbalanced quotes, drop the
    quote characters rather than showing a stray one.
    """
    parts, buf, in_q = [], '', False
    for ch in page:
        buf += ch
        if ch == '"':
            in_q = not in_q
        elif ch in '.!?' and not in_q:
            parts.append(buf.strip())
            buf = ''
    if buf.strip():
        parts.append(buf.strip())

    out = []
    for p in parts:
        p = p.strip()
        if not p:
            continue
        # a closing quote/punctuation belonging to the previous sentence
        p = re.sub(r'^[",\s]+', '', p)
        if p.count('"') % 2:
            p = p.replace('"', '')
        p = re.sub(r'\s+', ' ', p).strip()
        if p:
            out.append(p)
    return out


def read(p):
    return open(os.path.join(ROOT, p), encoding='utf-8').read()


# Bank filler that has no business on a practice card: non-words ('hup',
# 'bubby'), archaic or odd picks ('bane', 'bard', 'coo'), and brand-ish
# words ('coke'). The banks needed decodable letter patterns; this app
# shows the word to a child, which is a higher bar.
EXCLUDE = {'hup', 'bane', 'bard', 'coke', 'coo', 'bubby'}


def main():
    man = json.load(open(os.path.join(ROOT, 'classic/audio/manifest.json')))

    words = {1: set(), 2: set(), 3: set()}
    for lvl in (1, 2, 3):
        src = read(f'classic/js/curriculum-l{lvl}.js')
        for m in re.finditer(r"word:\s*'([a-z]+)'", src):
            words[lvl].add(m.group(1))
        for m in re.finditer(r"mastery:\s*\[([^\]]+)\]", src):
            for w in re.findall(r"'([a-z]+)'", m.group(1)):
                words[lvl].add(w)
    bank = read('classic/js/banks.js')
    for m in re.finditer(r"'(L(\d))-\d+'\s*:\s*\[([^\]]+)\]", bank):
        lvl = int(m.group(2))
        for w in re.findall(r"'([a-z]+):", m.group(3)):
            words[lvl].add(w)

    def sentences_from(src, get_level):
        out = []
        for sm in re.finditer(r"id:\s*'([A-Z0-9-]+)'", src):
            seg = src[sm.start():]
            pm = re.search(r"pages:\s*\[(.*?)\n\s*\],", seg, re.S)
            if not pm:
                continue
            lvl = get_level(sm.group(1), seg)
            for x in re.finditer(r"'((?:[^'\\]|\\.)*)'", pm.group(1)):
                page = x.group(1).replace("\\'", "'")
                for s in split_sentences(page):
                    n = len(re.findall(r"[A-Za-z']+", s))
                    if 3 <= n <= 12 and s:
                        out.append((lvl, s))
        return out

    sents = []
    for lvl in (1, 2, 3):
        sents += sentences_from(read(f'classic/js/curriculum-l{lvl}.js'),
                                lambda sid, seg, l=lvl: l)
    sents += sentences_from(
        read('classic/js/storylib.js'),
        lambda sid, seg: int((re.search(r"level:\s*(\d)", seg[:400]) or [None, '2'])[1]))

    def wclip(w):
        f = man['words'].get(w)
        return 'classic/audio/' + f if f else None

    data = {'words': {}, 'sentences': {}}
    for lvl in (1, 2, 3):
        ws = sorted(w for w in words[lvl] if 2 < len(w) <= 12 and w not in EXCLUDE)
        data['words'][str(lvl)] = [{'t': w, 'a': wclip(w)} for w in ws]
        seen, arr = set(), []
        for l, s in sents:
            if l == lvl and s.lower() not in seen:
                seen.add(s.lower())
                arr.append({'t': s})
        data['sentences'][str(lvl)] = arr

    out = os.path.join(ROOT, 'content.js')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('// Graded reading content, generated by dev/build_content.py from the\n')
        f.write('// classic curriculum. Every word clip was transcription-verified.\n')
        f.write('const CONTENT = ' + json.dumps(data, separators=(',', ':')) + ';\n')
    for lvl in (1, 2, 3):
        print(f"L{lvl}: {len(data['words'][str(lvl)])} words, "
              f"{len(data['sentences'][str(lvl)])} sentences")
    print('wrote', out)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
